public enum EventID
{

    NONE,
    //HOME SCRENE
    CHANGE_COIN = 50,
    CHANGE_HEART = 51,

    BOOSTER_USE_REQUEST = 100,
    BOOSTER_CANCEL_REQUEST = 1101,

    BLOCK_DESTROYED = 200,
    LEVEL_COMPLETE = 201,
    SHOOTER_FIRED = 202,
    LOOP_MODE_ENTERED = 203,
    CONVEYOR_NOT_ENOUGH_SLOT = 204

}
